language: generic
sudo: required
dist: trusty
notifications:
email: false
os: linux
install:
- node -v
- npm install -g danger
- eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
- swiftenv install 4.0
- swiftenv global 4.0 # https://github.com/danger/danger-swift/issues/63
- git clone https://github.com/danger/danger-swift.git
- cd danger-swift && make install
script:
- danger process danger-swift
