language: generic
sudo: required
dist: trusty
notifications:
email: false
os: linux
install:
- node -v
- npm install -g danger
- eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
- swiftenv global 4.1
script:
- danger process danger-swift
